### ISSUE TITLE
Community Documents

### ISSUE THREAD

**Issue by thejessleigh** [Alamantus/local-rpg#2]
Hey y'all. This project looks awesome. I might want to poke around on it sometime if you're open to that. It would be very helpful to have a license, code of conduct, and contribution guidelines though. Thanks for creating this project! :)

**Comment by Alamantus** [comment]
Thanks! We'd definitely love some help on it, but for now, we're still setting up the framework and getting the design hammered out—right now, there's a lot of movement on the server and electron setup and not much consistency to create guidelines from.

Once it's got a more solid base, I'll definitely set up all of those docs so more people can help out! I'll keep this issue open so I don't forget. :+1:

**Comment by descartez** [comment]
We can update the docs for contributions! Thanks for the input Jess!

**Comment by Alamantus** [comment]
Hey @thejessleigh, I just pushed the community docs to master!

There's still a little more scaffolding that needs to be done, but there's enough in place that it should be easy to follow the ideas.

Hope you still want to join in!
